# This is a basic workflow to help you get started with Actions
- name: 'Create env file'
        run: |
          touch .env
          echo VITE_GRAPHQL_API=https://api-eu-central-1.hygraph.com/v2/cl52fv46h25eg01ujhpnjc820/master >> .env
          echo VITE_USERNAME = "admin" >> .env
          echo VITE_PASSWORD = "admin" >> .env
          echo VITE_MONGO_URL="mongodb://192.168.0.250:27017" >> .env

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  VITE_GRAPHQL_API: ${{ secrets.GARPHQL }}
  VITE_USERNAME: ${{ secrets.USERNAME }}
  VITE_PASSWORD: ${{ secrets.PASSWORD }}
  VITE_MONGO_URL: ${{ secrets.MONGO }}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: self-hosted
    # runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Use Nodes.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
      - run: pm2 restart Portfolio
